List battles and its details
vanessa/pokebattle pull request #6
Opened 2018-04-24 19:24 UTC by vanessa

## Description

- Refine battle listing (it was previously basic and confusing)
- Refine battle detail page

> Notes: Probably there are some files that aren't directly related to the PR. It's because I created the branch based on `add-battle-logic`, my bad, sorry.

## Motivation and Context

The current battle listing template gets really confusing when you create/is invited to battles ([see here](https://user-images.githubusercontent.com/23136832/39208848-6fca0d7a-47da-11e8-89e9-a675649fd883.png)).

- https://trello.com/c/JsJvZEz6/2-as-a-trainer-i-see-a-list-of-settled-battles
- https://trello.com/c/CEmB7DzM/8-as-a-trainer-i-see-a-list-of-on-going-battles
- https://trello.com/c/iYg3Wh3w/9-as-a-trainer-i-see-the-details-of-a-settled-battle

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/23136832/39208057-2c6e1c9e-47d8-11e8-9ebf-fb8ca1bbe0a6.png)
> Battle list

![image](https://user-images.githubusercontent.com/23136832/39208064-37bfe12c-47d8-11e8-85e2-8eac58949a75.png)
> Battle details

## Steps to reproduce (if appropriate):

## Critical points affected:

- [ ] Signup flow
- [ ] Battle creation
- [ ] Battle team choosing
- [ ] Battle execution

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt (refactoring existing code)

## Checklist:

- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires dependencies updates.
- [ ] I have updated the dependencies accordingly.
- [ ] My change affected critical flows & code.
- [ ] I have tested the critical flows & code accordingly.
- [ ] My change requires environment variables updates.
- [ ] I have described the environment variables accordingly.

2018-04-30 01:40 UTC, lucabezerra commented on battles/helpers/battle.py
> +    result = {}
Nothing wrong with doing it this way, but you could also do it in a cleaner way:
```
result = {
    'creator_team': [pokemon.id for pokemon in creator_team.pokemons.all()],
    'opponent_team': [pokemon.id for pokemon in opponent_team.pokemons.all()],
}
```

2018-04-30 01:57 UTC, lucabezerra commented on battles/helpers/battle.py
> +def get_the_battle_winner(battle):
In general, it's better to avoid putting articles ('the') in method names, unless you actually need to explicit something :)

2018-04-30 02:02 UTC, lucabezerra commented on battles/helpers/battle.py
> +    if can_run_battle(battle):
Try to always follow the "guard clause" pattern in methods that have checks for performing its main action (see: https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).

In this case, we'd first assess the case where the method's main action is not performed:
```
if not can_run_battle(battle):
    return False
```
And then the rest of the method would not need to be indented in an `if` block:
```
winner = get_the_battle_winner(battle)
battle.winner = winner
battle.status = 'F'
battle.save()
send_email_when_battle_finishes(battle)
return True
```
 This helps improving legibility :)

2018-04-30 02:03 UTC, lucabezerra commented on battles/helpers/battle.py
> +def teams_cannot_battle(first_team, second_team):
Again, try to apply the guard clause pattern here :)

2018-04-30 03:08 UTC, lucabezerra requested changes
Your application is looking good! :)

I've requested a few changes here and there, though. Mostly are just renaming methods and variables. Naming is a super simple thing in theory, but can be super challenging in practice. When naming things, we should always strive for 2 things: consistency and clarity. It helps **a lot** for someone to read your code, even if it's yourself reading it a few weeks/months from now.

Also, I think your code would look better to read/cleaner if you'd fit the commands in one single line whenever possible.
We tend to work with 100 characters long lines (some places still use 80 chars, but I think that's exaggerating) and we break the line only if the command doesn't fit whole in a single line. That's usually the case in an `if` statement with long variable names or a method call that has lots of parameters. Otherwise, it looks better (in my opinion, but I'd risk saying it's somewhat a consensus) to write it in a single line :)

Let me know if you have any questions! Nice work!

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +    result = {}
Nothing wrong with doing it this way, but you could also do it in a cleaner way:
```
result = {
    'creator_team': [pokemon.id for pokemon in creator_team.pokemons.all()],
    'opponent_team': [pokemon.id for pokemon in opponent_team.pokemons.all()]
}
```

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +def get_the_battle_winner(battle):
In general, it's better to avoid putting articles ('the') in method names, unless you actually need to explicit something :)

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +    if can_run_battle(battle):
Try to always follow the "guard clause" pattern in methods that have checks for performing its main action (see: https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).

In this case, we'd first assess the case where the method's main action is not performed:
```
if not can_run_battle(battle):
    return False
```
And then the rest of the method would not need to be indented in an `if` block:
```
winner = get_the_battle_winner(battle)
battle.winner = winner
battle.status = 'F'
battle.save()
send_email_when_battle_finishes(battle)
return True
```
 This helps improving legibility :)

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +    if first_team:
Again, try to apply the guard clause pattern here :)

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +def battle_team_existent(battle, second_team):
I'm a little confused by what this method should do, based only in its name and the variable names. Do you think you could name both the method and the variables differently in any way, so that it's intentions are clearer?

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +def teams_cannot_battle(first_team, second_team):
This method's name seems to indicate that whatever action is done in it considers that it's already certain that the teams cannot battle. What do you think about renaming it to something like `can_teams_battle`?

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/emails.py
> +    for trainer in [battle.creator, battle.opponent]:
Just a suggestion:
Perhaps you could create a helper method in the `Battle` model, something like `get_participants`, which returns `[battle.creator, battle.opponent]`, so you don't have to explicitly write it whenever you want to reference both of them at once.

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/fight.py
> +def get_pokemon_winner(creator_pokemon, opponent_pokemon):
I believe this should have the words inverted, `get_winner_pokemon`, what do you say?

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/fight.py
> +def check_tie_and_return_winner(creator_pokemon, opponent_pokemon):
This is just a suggestion again, sorry if I sound annoying, haha. What do you think about calling this method `compare_status_and_return_winner`?
I've noticed your `check_` methods usually return `True` or `False`, we should always strive for consistency when writing code, so using `check_` on this one might be misleading.

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/fight.py
> +def compare_two_pokemons(creator_pokemon_id, opponent_pokemon_id):
Adding to the comment above, maybe we could merge this method with the `check_tie_and_return_winner` and have a single method, something like `compare_two_pokemons_and_return_winner`. 
I'm suggesting merging the methods because this one alone doesn't seem to do anything that needs to be separated from the other method. This is mostly a stylish suggestion, which may vary from developer to developer, so feel free to do as you prefer :)

2018-04-30 03:08 UTC, lucabezerra commented on battles/helpers/battle.py
> +def check_run_battle_and_save_winner(battle):
I find this method's name a bit confusing... I don't think we need to explicit that it runs `check_run_battle` in its name. Also, if we're being so explicit about what it does (run battle, save winner), we should also mention that it sends an email, which would make the name look even more confusing.
Maybe we should think of a better name to explain what this method does. It seems to me that this is the main method of this project, some sort of starting point or almost that. Could we think of a more generic name for it? Something like `run_battle`, `process_battle` or something along those lines?

2018-04-30 03:08 UTC, lucabezerra commented on battles/validators.py
> +def validate_integer_doesnt_start_with_zero(value):
I don't know if this was a requirement, but I'll suggest it in a way that works for both possibilities:

1. If displaying this error was not a requirement, what do you think about fixing the user input (i. e. removing the starting `0` if there is one and throwing an error only if there's no other number after the 0 was removed?
2. If it was a requirement, what do you think about suggesting this change to your client? As programmers, we often tend to think that we're just meant to implement the instructions that have been passed to us. However, at Vinta, we are also Consultants, in the sense that we're always trying to provide the most value to our client's product. This includes suggesting changes from what the client asked for, if we think it could benefit the product somehow.

Either way, I'm suggesting this as a better UX (user experience), which is a point you can use when/if suggesting it to the client. As a user, I'd rather not have to worry about typing with a starting `0` or not, getting error messages is annoying and I should only get that when I actually do something wrong :)

2018-04-30 16:53 UTC, vanessa commented on battles/validators.py
> +def validate_integer_doesnt_start_with_zero(value):
I agree, I'm gonna suggest that to Rob in our next meeting.

2018-04-30 19:07 UTC, vanessa commented on battles/helpers/battle.py
> +    result = {}
Much better!

2018-04-30 20:34 UTC, vanessa commented on battles/helpers/fight.py
> +def get_pokemon_winner(creator_pokemon, opponent_pokemon):
Exactly, my bad.

2018-04-30 21:21 UTC, vanessa commented on battles/helpers/fight.py
> +def check_tie_and_return_winner(creator_pokemon, opponent_pokemon):
Definitely not annoying, you're helping me to have a good code! :slightly_smiling_face:

2018-05-02 18:29 UTC, vanessa commented on battles/validators.py
> +def validate_integer_doesnt_start_with_zero(value):
Hi, Luca! I've talked to Rob and he agreed with your suggestion. However, I've noticed (and showed you) that the API already parses the Pokemon id the right way (?), that means, no matter how many zeros I put before my id, it'll work, [check it](https://pokeapi.co/api/v2/pokemon/0000002).

2018-05-02 18:38 UTC, vanessa commented
@lucabezerra I'm a bit confused with the flow. I've added a validator to ensure a user never picks a Pokemon with id 0 [here](https://github.com/vanessa/pokebattle/pull/6/files#diff-ceaca288d71d6174abeed396af477775R13), the problem is: for some reason, my `clean()` never gets there, it seems to ignore it (I've tried using ipdb).

So, I had to put the validation manually [here](https://github.com/vanessa/pokebattle/pull/6/files#diff-049c26f7d794fd3dfeb0d6fdce646858R61) because my code fails when it gets [here](https://github.com/vanessa/pokebattle/pull/6/files#diff-049c26f7d794fd3dfeb0d6fdce646858R71), but for me it doesn't solve the problem the way I'd like to, I'd like to show an error to the user saying exactly what Pokemon is invalid, but my individual clean methods (`clean_first_pokemon()`, ...) never run before the `clean()` itself.

For the way it is now, it's working and the tests are passing, but I'm clueless about validating individually. Do you have any idea why this is happening?

2018-05-02 20:42 UTC, vanessa commented
@lucabezerra Nevermind, I figured out with Anderson the Django's default validation flow. It's supposed to work like that.

2018-05-02 20:55 UTC, lucabezerra commented
Sorry for the delay, but I'm glad that you've managed to work it out, nice job!

2018-05-07 17:31 UTC, lucabezerra approved these changes
Great job!

2018-05-07 17:32 UTC, merged